---
title: "Midterm"
author: "Alexis Adams-Clark"
date: "4/23/2019"
output: html_document
---

```{r Part A setup, message = FALSE, warning = FALSE, error = FALSE}

#Part A setup

#install.packages("glue")
library(tidyverse)
library(rio)
library(glue)
library(purrr)
library(janitor)
library(repurrrsive)

knitr::opts_chunk$set(message = FALSE, error = FALSE, warning = FALSE)
```


```{r A Question 1}

#PART A:

#Question A.1: Use the function above to download all the data for each of the past 4 school years and bind it into a single data frame, using a single function (i.e., one line of code). Note, this may take a minute or two to run, depending on your Internet speed.

download_file <- function(year) {
    link <- glue::glue("https://www.oregon.gov/ode/educator-resources/assessment/TestResults20{year}/pagr_schools_ela_raceethnicity_{year-1}{year}.xlsx")
    rio::import(link, setclass = "tibble", na = c("-", "--", "*"))
}

data <- map_df(c(15:18), download_file)

#Conduct some basic data cleaning to make your data file look like the following. Filter for only student groups coded as "White" or "Hispanic/Latino". Select variables related to the number of students in each of the levels (1:4), and not percentages or collapsed levels. Remove any row that has missing data in any of the n variables.

data <- data %>% 
  clean_names() %>% 
  filter(student_group == "White" | student_group == "Hispanic/Latino") %>% 
  select(academic_year, district, school, student_group, grade_level, number_level_1, number_level_2, number_level_3, number_level_4)

gathered1 <- data %>% 
  gather(level, n, 6:9) %>% 
  filter(!is.na(n)) %>% 
  mutate(level = parse_number(level)) %>% 
  mutate(grade_level = parse_number(grade_level)) %>% 
  arrange(academic_year, district, student_group, grade_level)
gathered1

```


```{r A Question 2}

#Question A.2: Calculate the cumulative n for each school by student group, grade, and academic year. 

gathered2 <- gathered1 %>%
  group_by(school, student_group, grade_level, academic_year) %>% 
  mutate(cn = cumsum(n))
gathered2
head(gathered2)
  
```


```{r A Question 3}

#Question A.3: Reformat the data so it looks like the below, removing n and filling by cn. Remove rows that have missing data for either student group.

gathered3 <- gathered2 %>%
  select(-n) %>% 
  spread(student_group, cn) %>% 
  clean_names() %>%
  filter(!is.na(hispanic_latino)) %>% 
  filter(!is.na(white))
gathered3
head(gathered3)

```


```{r Part B setup}

#PART B

#Part B setup

#install.packages("pracma")
library(pracma)

gap <- function(data, ref, foc) {
    x <- data[[ref]]
    y <- data[[foc]]
    auc <- pracma::trapz(y / y[length(x)],
                         x / x[length(x)])
    sqrt(2)*qnorm(auc)
}
```


```{r B Question 1}

#Question B.1: Estimate an achievement gap effect size for every school in the state that reported data on both student groups (i.e., using the data we created above), for each grade level in each academic year.

#Example: 
d <- gathered3

gap(d[1:4, ], "white", "hispanic_latino")

by_school_grade <- d %>%
    nest(-school, -grade_level, -academic_year)

df <- by_school_grade %>% 
  mutate(gap = map_dbl(data, gap, "white", "hispanic_latino")) 
df

str(by_school_grade$data[[1]])
```


```{r B Question 2}

#Question B.2: The plot below shows the achievement gap estimates for one school by grade in Ashland School District during the 2017-18 school year. Produce a similar plot to the below (noting the school, academic year, and school district) for each of the first 100 unique school/year/district combinations. Hint - you’ll want to use your effect size data from from the previous question, nest it, then apply slice(1:100). 

extract_dist <- function(ob) {
    ob[["district"]][1]
}

#install.packages("rcartocolor")
library(rcartocolor)

#Ehh...I tried to remove all the weird "SD" and "4J" characters, and I managed to get most of them. But it sure is difficult!
plots <- df %>% 
  mutate(district = map_chr(data, extract_dist)) %>% 
  mutate(district = str_replace_all(district, "SD", "")) %>% 
  mutate(district = str_replace_all(district, '[[:digit:]]+', "")) %>% 
  mutate(district = str_replace_all(district, " J", "")) %>% 
  mutate(district = str_replace_all(district, 'J ', "")) %>% 
  select(-data) %>% 
  group_by(school, district, academic_year) %>% 
  nest() %>% 
  slice(1:100) %>% 
  mutate(plot = pmap(list(data, school, district, academic_year), ~
          ggplot(..1, aes(grade_level, gap, fill = gap)) +
          geom_col() +
          coord_flip() + 
          scale_fill_carto_c(palette = "Earth", direction = -1, limits= c(-1.5, 1.5)) + 
          theme_minimal() +
          geom_hline(yintercept = 0, size = 1, color = "Black") +
          theme(legend.position = "bottom", legend.key.width = unit(3, "cm"), legend.title = element_blank()) +
          labs(title = glue("Achievement Gap Estimates: {..2}"), subtitle = "Students coded as White as compared to those coded as Hispanic/Latino\n", caption = glue("{..4} School year, {..3} School District, Oregon"), y = "\nEffect Size", x = "Grade\n")))

#Testing first 10 plots
plots$plot[1:10]

#I know that you did your zero line in a bluish color (like #ADC3B6), but I liked it better black. (:



##To check mine against your example in the assignment....
exampleplot <- df %>% 
  mutate(district = map_chr(data, extract_dist)) %>% 
  select(-data) %>% 
  group_by(school, district, academic_year) %>% 
  nest() %>% 
  filter(school == "Ashland Middle School") %>% 
  mutate(plot = map2(data, school, ~
          ggplot(.x, aes(grade_level, gap, fill = gap)) +
          geom_col() +
          coord_flip() + 
          scale_fill_carto_c(palette = "Earth", direction = -1, limits= c(-1.5, 1.5)) + 
          theme_minimal() +
          geom_hline(yintercept = 0, size = 1, color = "#ADC3B6") +
          theme(legend.position = "bottom", legend.key.width = unit(3, "cm"), legend.title = element_blank()) +
          labs(title = glue("Gap: {.y}"),  y = "\nEffect Size", x = "Grade\n", subtitle = "Students coded as White as compared to those coded as Hispanic/Latino\n")))
exampleplot$plot[[4]]
#looks the same WOO

```

```{r B Question 3}

#Question B.3: Save the plots into a “plots” directory. Make sure the file names are meaningful.
#create new plot folder
df_save <- plots %>% 
  unite(file, school, academic_year, sep = "_")

fs::dir_create(here::here("plots"))
files <- str_replace_all(tolower(df_save$file), " ", "_")
paths <- here::here("plots", glue("{files}.png"))

walk2(paths, df_save$plot, ggsave,
      width = 9.5, 
      height = 6.5,
      dpi = 500)
```